export var registrationData = {
    email: "",
    password: "",
    firstName: "",
    lastName: "",
    dob: "",
    gender: "",
    contact: null,
    country: "",
    highSchoolBoard: "",
    highSchoolSchool: "",
    highSchoolPercentage: null,
    intermediateBoard: "",
    intermediateSchool: "",
    intermediatePercentage: null,
    universityName: "",
    graduationCourse: "",
    graduationBranch: "",
    graduationPercentage: null,
    agreement: false,
}
